Repository nathanheinzmann/validator, pull requests merged in 2021-03, with the labels that each got.

#1 Feat/response
  .github/pull_request_template.md
  README.old.md
  package.json
  src/components/Response/index.tsx
  src/components/Response/styles.ts
  src/components/index.ts
  yarn.lock
Labels: Feature

#2 Rules Added
  src/components/Rules/index.tsx
  src/components/Rules/styles.ts
  src/components/index.ts
Labels: feature

#3 created input component and editor config
  .editorconfig
  src/components/Input/index.tsx
  src/components/Input/styles.ts
  src/components/index.ts
Labels: feature

#6 Feat/add context
  src/App.tsx
  src/components/Input/index.tsx
  src/components/Response/index.tsx
  src/components/Response/styles.ts
  src/contexts/ValueInserted.tsx
  src/contexts/index.ts
Labels: feature

#7 mergear a develop pra main
  .editorconfig
  .github/pull_request_template.md
  README.old.md
  package.json
  src/App.tsx
  src/components/Input/index.tsx
  src/components/Input/styles.ts
  src/components/Response/index.tsx
  src/components/Response/styles.ts
  src/components/Rules/index.tsx
  src/components/Rules/styles.ts
  src/components/index.ts
  src/contexts/ValueInserted.tsx
  src/contexts/index.ts
  src/utils/helpers/index.ts
  src/utils/helpers/validator.ts
  src/utils/index.ts
  yarn.lock
Labels: task

#8 finished
  src/App.css
  src/App.tsx
  src/components/Input/styles.ts
  src/components/Response/index.tsx
  src/components/Response/styles.ts
  src/components/Rules/styles.ts
Labels: feature
